### ISSUE TITLE
What I wrote about Continuous integration with Travis CI

### ISSUE THREAD

**Issue by kkkk-source** [andresggz/arq-software-udea#1]
What do you think about these lines? we're talking about **Travis CI**.
Does it look good or would you like add something more?

https://github.com/andresggz/arq-software-udea/blob/1d1a10a49882e03a4d8dc2c516536ad8a94533d8/tex/git-github-maven-gradle.tex#L36-L38

**Comment by kkkk-source** [comment]
I've catched a mistake, I wrote "continous" instead of "continuous". There could be a lot of mistakes but don't worry. They will be fixed at the final.

**Comment by andresggz** [comment]
LGTM!
